# Generated by Django 4.2 on 2023-04-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0003_alter_user_name_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('units', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('price', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
    ]
