# Generated by Django 4.2 on 2023-05-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0004_order_delete_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='video_bg_color',
            field=models.CharField(default='default', max_length=10),
        ),
    ]
