# Generated by Django 4.2 on 2023-05-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0007_alter_order_expire_date_alter_order_pay_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('count_percent', models.IntegerField(default=0)),
            ],
        ),
    ]
