# Generated by Django 4.2 on 2023-04-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0007_alter_bills_duration_alter_user_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='body',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
