# Generated by Django 4.2 on 2023-04-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0009_housecase_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housecase',
            name='user',
        ),
    ]
