# Generated by Django 4.2 on 2023-06-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0009_coupon_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='housecase',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
