# Generated by Django 4.2 on 2023-04-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0012_housecase_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='video_id',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
