# Generated by Django 4.2 on 2023-04-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0013_user_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
    ]
