# Generated by Django 4.2 on 2023-05-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0015_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='plan',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
