# Generated by Django 4.2 on 2023-05-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0016_bills_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='duration',
        ),
        migrations.AddField(
            model_name='bills',
            name='time_period',
            field=models.IntegerField(default=0),
        ),
    ]
