version: '3.1'
services:
  db:
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
       - "127.0.0.1:5432:5432"
    volumes:
       - ./data:/var/lib/postgresql/data